# Use Node.js configuration.
language: node_js

# Both latest Node.js and latest LTS.
node_js: 
  - lts/current
  - lts/active
  - node

# All of the operating systems!
# Note: Windows support is very iffy.
os:
  - linux
  - osx
  - windows

# This keeps Yarn from hanging the build.
env:
  - YARN_GPG=no
